#!/usr/bin/env bash
set -e
make -j
for algorithm in passiveAgressive
do
    echo $algorithm.tsv > $algorithm.tsv
    time ./homework1.app mnist-training-set-5k.dat $algorithm >> $algorithm.tsv
    cat $algorithm.tsv
done
